import { IBook } from "./Models/Book"; // skapa en array av "IBooks"
export const books: IBook[] = [
  {
    id: 389,
    title: "The Travelling Cat Chronicles",
    author: "Hiro Arikawa",
    cover:
      "https://image.bokus.com/images/9780857526335_383x_the-travelling-cat-chronicles",
    year: 2024,
    format: "Pocket",
    genre: "Some genre",
    pages: 199,
    lang: "English",
    description: "Some descr...",
    price: 182,
    discount: 0,
    stock: 100,
  },
  {
    id: 390,
    title: "Cats in Hats",
    author: "Jo Clark",
    cover: "https://s1.adlibris.com/images/57824764/cats-in-hats.jpg",
    year: 2024,
    format: "Pocket",
    genre: "Some genre",
    pages: 199,
    lang: "English",
    description: "Some descr...",
    price: 182,
    discount: 0,
    stock: 100,
  },
  {
    id: 211,
    title: "Cats Galore",
    author: "Susam Herbert",
    cover: "https://image.bokus.com/images/9780500239360_383x_cats-galore",
    year: 2024,
    format: "Pocket",
    genre: "Some genre",
    pages: 199,
    lang: "English",
    description: "Some descr...",
    price: 211,
    discount: 0,
    stock: 100,
  },
  {
    id: 212,
    title: "The Blanket Cats",
    author: "Kiyoshi Shigematsu",
    cover: "https://s1.adlibris.com/images/69129281/the-blanket-cats.jpg",
    year: 2024,
    format: "Pocket",
    genre: "Some genre",
    pages: 199,
    lang: "English",
    description: "Some descr...",
    price: 173,
    discount: 0,
    stock: 100,
  },
  {
    id: 213,
    title: "Fire and Ice",
    author: "Erin Hunter",
    cover: "https://s2.adlibris.com/images/5761385/fire-and-ice.jpg",
    year: 2006,
    format: "Pocket",
    genre: "Some genre",
    pages: 352,
    lang: "English",
    description: "Some descr...",
    price: 126,
    discount: 0,
    stock: 100,
  },
  {
    id: 214,
    title: "Darkest Hour",
    author: "Erin Hunter",
    cover: "https://s2.adlibris.com/images/4205512/darkest-hour.jpg",
    year: 2008,
    format: "Pocket",
    genre: "Some genre",
    pages: 368,
    lang: "English",
    description: "Some descr...",
    price: 126,
    discount: 0,
    stock: 100,
  },
  {
    id: 215,
    title: "Rising Storm",
    author: "Erin Hunter",
    cover: "https://s1.adlibris.com/images/4407882/rising-storm.jpg",
    year: 2006,
    format: "Pocket",
    genre: "Some genre",
    pages: 320,
    lang: "English",
    description: "Some descr...",
    price: 126,
    discount: 0,
    stock: 100,
  },
  {
    id: 66,
    title: "Letters To The Human Race From the Cat",
    author: "Vicky Halls",
    cover:
      "https://image.bokus.com/images/9781788405546_383x_letters-to-the-human-race-from-the-cat",
    year: 2024,
    format: "Pocket",
    genre: "Some genre",
    pages: 199,
    lang: "English",
    description: "Some descr...",
    price: 167,
    discount: 0,
    stock: 100,
  },
  {
    id: 67,
    title: "Lilla veterinärskolan - din katt från nos till svans!",
    author: "Sara Klinga Myr",
    cover:
      "https://image.bokus.com/images/9789189083592_200x_lilla-veterinarskolan-din-katt-fran-nos-till-svans",
    year: 2023,
    format: "Pocket",
    genre: "Some genre",
    pages: 37,
    lang: "Swedish",
    description: "Some descr...",
    price: 138,
    discount: 0,
    stock: 100,
  },
  {
    id: 68,
    title: "If Cats Disappeared From The World",
    author: "Genki Kawamura",
    cover:
      "https://image.bokus.com/images2/9781509889174_medium_if-cats-disappeared-from-the-world",
    year: 2018,
    format: "Pocket",
    genre: "Some genre",
    pages: 208,
    lang: "English",
    description: "Some descr...",
    price: 141,
    discount: 0,
    stock: 100,
  },
  {
    id: 69,
    title: "The Goodbye Cat",
    author: "Hiro Arikawa",
    cover:
      "https://image.bokus.com/images2/9780857529138_medium_the-goodbye-cat",
    year: 2018,
    format: "Pocket",
    genre: "Some genre",
    pages: 256,
    lang: "English",
    description: "Some descr...",
    price: 159,
    discount: 0,
    stock: 100,
  },
  {
    id: 70,
    title: "All Cats Are on the Autism Spectrum",
    author: " Kathy Hoopmann",
    cover:
      "https://image.bokus.com/images/9781787754713_200x_all-cats-are-on-the-autism-spectrum",
    year: 2010,
    format: "Pocket",
    genre: "Some genre",
    pages: 80,
    lang: "English",
    description: "Some descr...",
    price: 190,
    discount: 0,
    stock: 100,
  },
  {
    id: 71,
    title: "The Blanket Cats",
    author: "Kiyoshi Shigematsu",
    cover:
      "https://image.bokus.com/images2/9781529435238_medium_the-blanket-cats",
    year: 2024,
    format: "Pocket",
    genre: "Some genre",
    pages: 150,
    lang: "English",
    description: "Some descr...",
    price: 175,
    discount: 0,
    stock: 100,
  },
  {
    id: 72,
    title: "On Cats",
    author: "Doris Lessing",
    cover: "https://image.bokus.com/images2/9780007285518_medium_on-cats",
    year: 2008,
    format: "Pocket",
    genre: "Some genre",
    pages: 150,
    lang: "English",
    description: "Some descr...",
    price: 139,
    discount: 0,
    stock: 100,
  },
  {
    id: 73,
    title: "The Age of Cats",
    author: "Jonathan B Losos",
    cover:
      "https://image.bokus.com/images2/9780008339500_medium_the-age-of-cats",
    year: 2024,
    format: "Pocket",
    genre: "Some genre",
    pages: 134,
    lang: "English",
    description: "Some descr...",
    price: 169,
    discount: 0,
    stock: 100,
  },

  {
    id: 74,
    title: "The Inner Life of Cats",
    author: "Thomas McNamee",
    cover:
      "https://image.bokus.com/images/9780316262903_200x_the-inner-life-of-cats_haftad",
    year: 2024,
    format: "Pocket",
    genre: "Some genre",
    pages: 288,
    lang: "English",
    description: "Some descr...",
    price: 189,
    discount: 0,
    stock: 100,
  },
  {
    id: 75,
    title: "Cat's Cradle",
    author: "Thomas McNamee",
    cover: "https://image.bokus.com/images2/9780241951606_medium_cats-cradle",
    year: 2011,
    format: "Pocket",
    genre: "Some genre",
    pages: 245,
    lang: "English",
    description: "Some descr...",
    price: 129,
    discount: 0,
    stock: 100,
  },
  {
    id: 76,
    title: "The Hidden Language of Cats",

    author: "Dr Sarah Brown",
    cover:
      "https://bilder.akademibokhandeln.se/images_akb/9781405957960_383/the-hidden-language-of-cats",
    year: 2011,
    format: "Pocket",
    genre: "Some genre",
    pages: 168,
    lang: "English",
    description:
      "KNOW SOMEONE WHO LOVES CATS? THEN READ ON FOR THE PERFECT GIFT . . . This book should not be left in the company of dog-lovers Spectator ---- DO YOU EVER THINK YOUR CAT IS TRYING TO TELL YOU SOMETHING? Cat lovers know all too well how mysterious their feline friends can be. Descended from shy, solitary North African wild cats, domestic cats set up home with devoted owners across the world. But how did those wildcats of old creep into our homes and our hearts, convincing us to keep them warm, fed, and pampered? Quite simply, they learned to talk to us. Each chapter dives into a different form of communication, including: - Vocalisation - Tail signals - Scents - Rubbing Renowned cat behaviour scientist Dr. Sarah Brown reveals the previously unexplored secrets of cat communication, translating every meow and every blank stare. Her book will be perfect for any cat lover who wants to learn more about their companion. ---- PRAISE FOR THE HIDDEN LANGUAGE OF CATS Sarah Brown knows cats. A fascinating blend of real-life stories and science informed by her deep expertise, this book will both entertain and inform any cat-lover John Bradshaw, New York Times bestselling author of The Trainable Cat and Cat Sense Every cat lover wishes they could understand what their cat is thinking: This book will help you do just that! Highly-entertaining and evidence-based guide to how cats communicate and how to have a better relationship with the cat in your life' Dr. Mikel Delgado, PhD, Certified Applied Animal Behaviourist and coauthor of Total Cat Mojo 'Reading Dr Brown's book has only strengthened my love of and fascination with cats!' Olivia Petter, Independent",
    price: 129,
    discount: 0,
    stock: 100,
  },
  {
    id: 76,
    title: "The Cat and The City",
    author: "Nick Bradley",
    cover: "https://s1.adlibris.com/images/58879944/the-cat-and-the-city.jpg",
    year: 2021,
    format: "Häftad",
    genre: "Some genre",
    pages: 304,
    lang: "English",
    description: "Some descr...",
    price: 150,
    discount: 0,
    stock: 100,
  },
];
